#!/usr/bin/env python3
"""generate_workspace.py — Scaffold a new ultimate-runtime workspace."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

ANSI = not (sys.platform == "win32" and not sys.stdout.isatty())
GREEN  = "\033[32m" if ANSI else ""
YELLOW = "\033[33m" if ANSI else ""
RED    = "\033[31m" if ANSI else ""
RESET  = "\033[0m"  if ANSI else ""


def log(msg: str, color: str = "") -> None:
    print(f"{color}{msg}{RESET}")


WORKSPACE_DIRS = [
    "runtime",
    "vm",
    "parsers",
    "ai",
    "networking",
    "school/42",
    "benchmarks",
    "docs/conventions",
    "tools",
    "third_party",
    "build_system/cmake",
    ".github/workflows",
]

WORKSPACE_FILES = {
    "CMakeLists.txt": (
        "cmake_minimum_required(VERSION 3.24)\n"
        "project({name} VERSION 0.1.0)\n\n"
        "include(build_system/cmake/compiler_flags.cmake)\n"
    ),
    "README.md": "# {name}\n\n> Generated by generate_workspace.py\n",
    ".gitignore": "build/\n*.o\n*.a\n",
}


def scaffold(name: str, dest: Path, dry: bool) -> None:
    root = dest / name
    log(f"[workspace] Creating: {root}", YELLOW)

    for d in WORKSPACE_DIRS:
        p = root / d
        if not dry:
            p.mkdir(parents=True, exist_ok=True)
        log(f"  [dir]  {p.relative_to(dest)}", GREEN)

    for fname, template in WORKSPACE_FILES.items():
        p = root / fname
        content = template.format(name=name)
        if not dry:
            p.parent.mkdir(parents=True, exist_ok=True)
            if not p.exists():
                p.write_text(content)
        log(f"  [file] {p.relative_to(dest)}", GREEN)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("name", help="Workspace name")
    parser.add_argument("--dest", default=".", help="Parent directory (default: .)")
    parser.add_argument("--dry-run", action="store_true", help="Preview without creating")
    args = parser.parse_args()

    scaffold(args.name, Path(args.dest).resolve(), args.dry_run)
    if not args.dry_run:
        log("[OK] Workspace created.", GREEN)


if __name__ == "__main__":
    main()
