#!/usr/bin/env python3
"""generate_library.py — Scaffold a new C library inside runtime/."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

ANSI = not (sys.platform == "win32" and not sys.stdout.isatty())
GREEN  = "\033[32m" if ANSI else ""
YELLOW = "\033[33m" if ANSI else ""
RESET  = "\033[0m"  if ANSI else ""


def log(msg: str, color: str = "") -> None:
    print(f"{color}{msg}{RESET}")


def cmake_content(name: str) -> str:
    return f"""\
cmake_minimum_required(VERSION 3.24)
project({name} VERSION 0.1.0 LANGUAGES C)

include(../../build_system/cmake/compiler_flags.cmake)
include(../../build_system/cmake/warnings.cmake)

add_library({name} STATIC)

target_sources({name} PRIVATE
    src/{name}.c
)

target_include_directories({name}
    PUBLIC  ${{CMAKE_CURRENT_SOURCE_DIR}}/include/public
    PRIVATE ${{CMAKE_CURRENT_SOURCE_DIR}}/include/private
)

ur_set_compile_flags({name})
ur_enable_warnings({name} PRIVATE)

install(TARGETS {name}
    ARCHIVE DESTINATION lib
    INCLUDES DESTINATION include
)
"""


def makefile_content(name: str) -> str:
    return f"""\
NAME    = lib{name}.a
CC      = cc
CFLAGS  = -Wall -Wextra -Werror -std=c17
AR      = ar rcs
SRCS    = src/{name}.c
OBJS    = $(SRCS:.c=.o)

all: $(NAME)

$(NAME): $(OBJS)
\t$(AR) $(NAME) $(OBJS)

clean:
\trm -f $(OBJS)

fclean: clean
\trm -f $(NAME)

re: fclean all

.PHONY: all clean fclean re
"""


def header_content(name: str) -> str:
    guard = f"{name.upper()}_H"
    return f"""\
#ifndef {guard}
#define {guard}

#include <stddef.h>
#include <stdint.h>

/* {name} public API */

#endif /* {guard} */
"""


def source_content(name: str) -> str:
    return f"""\
#include "{name}/{name}.h"

/* {name} — implementation */
"""


def readme_content(name: str) -> str:
    return f"# {name}\n\n> Generated by generate_library.py\n"


def scaffold(name: str, dest: Path, dry: bool) -> None:
    root = dest / "runtime" / name
    log(f"[library] Creating: {root}", YELLOW)

    dirs = [
        root / "src",
        root / "tests",
        root / "include" / "public" / name,
        root / "include" / "private",
        root / "docs",
        root / "fuzz",
        root / "benchmarks",
    ]
    for d in dirs:
        if not dry:
            d.mkdir(parents=True, exist_ok=True)
        log(f"  [dir]  {d.relative_to(dest)}", GREEN)

    files = {
        root / "CMakeLists.txt":              cmake_content(name),
        root / "Makefile":                    makefile_content(name),
        root / "include" / "public" / name / f"{name}.h": header_content(name),
        root / "src" / f"{name}.c":           source_content(name),
        root / "README.md":                   readme_content(name),
    }
    for path, content in files.items():
        if not dry:
            path.parent.mkdir(parents=True, exist_ok=True)
            if not path.exists():
                path.write_text(content)
        log(f"  [file] {path.relative_to(dest)}", GREEN)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("name", help="Library name (e.g. libft)")
    parser.add_argument("--dest", default=".", help="Monorepo root (default: .)")
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args()

    scaffold(args.name, Path(args.dest).resolve(), args.dry_run)
    if not args.dry_run:
        log("[OK] Library scaffolded.", GREEN)


if __name__ == "__main__":
    main()
