#!/usr/bin/env python3
"""generate_application.py — Scaffold a standalone CLI application."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

ANSI = not (sys.platform == "win32" and not sys.stdout.isatty())
GREEN  = "\033[32m" if ANSI else ""
YELLOW = "\033[33m" if ANSI else ""
RESET  = "\033[0m"  if ANSI else ""


def log(msg: str, color: str = "") -> None:
    print(f"{color}{msg}{RESET}")


def cmake_content(name: str) -> str:
    return f"""\
cmake_minimum_required(VERSION 3.24)
project({name} VERSION 0.1.0 LANGUAGES C)

include(../../build_system/cmake/compiler_flags.cmake)
include(../../build_system/cmake/warnings.cmake)

add_executable({name} src/main.c)

target_include_directories({name} PRIVATE src)
ur_set_compile_flags({name})
ur_enable_warnings({name} PRIVATE)

install(TARGETS {name} RUNTIME DESTINATION bin)
"""


def main_c_content(name: str) -> str:
    return f"""\
#include <stdio.h>
#include <stdlib.h>

int main(int argc, char *argv[])
{{
    (void)argc;
    (void)argv;
    printf("{name}\\n");
    return EXIT_SUCCESS;
}}
"""


def readme_content(name: str) -> str:
    return f"# {name}\n\n> Generated by generate_application.py\n"


def scaffold(name: str, dest: Path, dry: bool) -> None:
    root = dest / name
    log(f"[application] Creating: {root}", YELLOW)

    dirs = [root / "src", root / "tests", root / "docs"]
    for d in dirs:
        if not dry:
            d.mkdir(parents=True, exist_ok=True)
        log(f"  [dir]  {d.relative_to(dest)}", GREEN)

    files = {
        root / "CMakeLists.txt":  cmake_content(name),
        root / "src" / "main.c": main_c_content(name),
        root / "README.md":       readme_content(name),
    }
    for path, content in files.items():
        if not dry:
            path.parent.mkdir(parents=True, exist_ok=True)
            if not path.exists():
                path.write_text(content)
        log(f"  [file] {path.relative_to(dest)}", GREEN)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("name", help="Application name")
    parser.add_argument("--dest", default=".", help="Parent directory (default: .)")
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args()

    scaffold(args.name, Path(args.dest).resolve(), args.dry_run)
    if not args.dry_run:
        log("[OK] Application scaffolded.", GREEN)


if __name__ == "__main__":
    main()
